CREATE DATABASE IF NOT EXISTS vehicle_inventory CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE vehicle_inventory;

CREATE TABLE IF NOT EXISTS vehicles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    year SMALLINT UNSIGNED NOT NULL,
    vin VARCHAR(17) NULL UNIQUE,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    status ENUM('available', 'sold', 'maintenance') NOT NULL DEFAULT 'available',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
